/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Validator;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author colep
 */
public class DVT extends javax.swing.JFrame {

    /**
     * Creates new form DVT
     */
    public DVT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SubjectList = new javax.swing.JComboBox<>();
        PastPaperChecker = new javax.swing.JCheckBox();
        DateTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GradeTextBox = new javax.swing.JTextField();
        TimeTextBox = new javax.swing.JTextField();
        FirstNameTextBox = new javax.swing.JTextField();
        LastNameTextBox = new javax.swing.JTextField();
        BookNowButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TimeErrorMessage = new javax.swing.JLabel();
        FirstNameErrorMessage = new javax.swing.JLabel();
        LastNameErrorMessage = new javax.swing.JLabel();
        GradeErrorMessage = new javax.swing.JLabel();
        DateErrorMessage = new javax.swing.JLabel();
        JobSuccesfulMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tutor Booking");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 56));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 56));

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Subject:");

        jLabel5.setText("Grade:");

        jLabel6.setText("Date:");

        jLabel7.setText("Time:");

        SubjectList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SubjectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Afrikaans", "English", "Coding", "Art", "Physics", "Biology", "Geography", "History" }));

        PastPaperChecker.setText("Past papers required?");
        PastPaperChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastPaperCheckerActionPerformed(evt);
            }
        });

        DateTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DateTextBox.setForeground(new java.awt.Color(153, 153, 153));
        DateTextBox.setToolTipText("");
        DateTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextBoxActionPerformed(evt);
            }
        });
        DateTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DateTextBoxKeyPressed(evt);
            }
        });

        GradeTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GradeTextBox.setForeground(new java.awt.Color(153, 153, 153));
        GradeTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeTextBoxActionPerformed(evt);
            }
        });
        GradeTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GradeTextBoxKeyPressed(evt);
            }
        });

        TimeTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TimeTextBox.setForeground(new java.awt.Color(153, 153, 153));
        TimeTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeTextBoxActionPerformed(evt);
            }
        });
        TimeTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TimeTextBoxKeyPressed(evt);
            }
        });

        FirstNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FirstNameTextBox.setForeground(new java.awt.Color(153, 153, 153));
        FirstNameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameTextBoxMouseClicked(evt);
            }
        });
        FirstNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextBoxActionPerformed(evt);
            }
        });
        FirstNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstNameTextBoxKeyPressed(evt);
            }
        });

        LastNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LastNameTextBox.setForeground(new java.awt.Color(153, 153, 153));
        LastNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextBoxActionPerformed(evt);
            }
        });
        LastNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameTextBoxKeyPressed(evt);
            }
        });

        BookNowButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BookNowButton.setText("Book Now");
        BookNowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookNowButtonMouseClicked(evt);
            }
        });

        TimeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        TimeErrorMessage.setText("    ");

        FirstNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        FirstNameErrorMessage.setText("    ");

        LastNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        LastNameErrorMessage.setText("     ");

        GradeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        GradeErrorMessage.setText("     ");

        DateErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        DateErrorMessage.setText("    ");

        JobSuccesfulMessage.setForeground(new java.awt.Color(51, 204, 0));
        JobSuccesfulMessage.setText("        ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel8)
                .addGap(101, 101, 101)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(FirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9))
                    .addComponent(FirstNameErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addComponent(LastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LastNameErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(GradeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(GradeErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(SubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addComponent(DateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(DateErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addComponent(TimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(TimeErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(PastPaperChecker))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(BookNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(JobSuccesfulMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(FirstNameErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameErrorMessage))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(GradeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(GradeErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(SubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(DateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateErrorMessage))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeErrorMessage))
                .addGap(20, 20, 20)
                .addComponent(PastPaperChecker)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(JobSuccesfulMessage))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PastPaperCheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastPaperCheckerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PastPaperCheckerActionPerformed

    private void DateTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTextBoxActionPerformed

    private void GradeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTextBoxActionPerformed

    private void TimeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeTextBoxActionPerformed

    private void FirstNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FirstNameTextBoxActionPerformed

    private void LastNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextBoxActionPerformed

    private void FirstNameTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameTextBoxMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FirstNameTextBoxMouseClicked

    private void FirstNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextBoxKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FirstNameTextBoxKeyPressed

    private void LastNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextBoxKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_LastNameTextBoxKeyPressed

    private void GradeTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GradeTextBoxKeyPressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_GradeTextBoxKeyPressed

    private void DateTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTextBoxKeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_DateTextBoxKeyPressed

    private void TimeTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TimeTextBoxKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TimeTextBoxKeyPressed

    private void BookNowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookNowButtonMouseClicked
       
        boolean pastpaper = PastPaperChecker.isSelected();
        
       
        //Format Check
        if(!Validator.ValidateDateFormat(DateTextBox.getText())){
            DateErrorMessage.setText("Please Input the correct Format of the Date");
        }
        
        
        
        //Presence Check
        
        if (FirstNameTextBox.getText().equalsIgnoreCase("")){
            FirstNameErrorMessage.setText("Enter First Name");
        }
        
        if (LastNameTextBox.getText().equalsIgnoreCase("")){
            LastNameErrorMessage.setText("Enter Last Name");
        }
        
        if (GradeTextBox.getText().equalsIgnoreCase("")){
            GradeErrorMessage.setText("Enter Grade");
        }
        
        if (DateTextBox.getText().equalsIgnoreCase("")){
            DateErrorMessage.setText("Enter Date");
        }
        
        if (TimeTextBox.getText().equalsIgnoreCase("")){
            TimeErrorMessage.setText("Enter Time");
        }
        
        
        
        
       
        
        
        
        
        
        
    }//GEN-LAST:event_BookNowButtonMouseClicked
  
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNowButton;
    private javax.swing.JLabel DateErrorMessage;
    private javax.swing.JTextField DateTextBox;
    private javax.swing.JLabel FirstNameErrorMessage;
    private javax.swing.JTextField FirstNameTextBox;
    private javax.swing.JLabel GradeErrorMessage;
    private javax.swing.JTextField GradeTextBox;
    private javax.swing.JLabel JobSuccesfulMessage;
    private javax.swing.JLabel LastNameErrorMessage;
    private javax.swing.JTextField LastNameTextBox;
    private javax.swing.JCheckBox PastPaperChecker;
    private javax.swing.JComboBox<String> SubjectList;
    private javax.swing.JLabel TimeErrorMessage;
    private javax.swing.JTextField TimeTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
