/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Validator;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author colep
 */
public class DVT extends javax.swing.JFrame {

    /**
     * Creates new form DVT
     */
    public DVT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SubjectList = new javax.swing.JComboBox<>();
        PastPaperChecker = new javax.swing.JCheckBox();
        DateTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GradeTextBox = new javax.swing.JTextField();
        HourTextBox = new javax.swing.JTextField();
        FirstNameTextBox = new javax.swing.JTextField();
        LastNameTextBox = new javax.swing.JTextField();
        BookNowButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TimeErrorMessage = new javax.swing.JLabel();
        FirstNameErrorMessage = new javax.swing.JLabel();
        LastNameErrorMessage = new javax.swing.JLabel();
        GradeErrorMessage = new javax.swing.JLabel();
        DateErrorMessage = new javax.swing.JLabel();
        SuccesfulMessage = new javax.swing.JLabel();
        MinTextBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 101, 50));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tutor Booking");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 56));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 56));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 143, 68));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 340, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subject:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Grade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Time:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        SubjectList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SubjectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Afrikaans", "English", "Coding", "Art", "Physics", "Biology", "Geography", "History" }));
        getContentPane().add(SubjectList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        PastPaperChecker.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        PastPaperChecker.setForeground(new java.awt.Color(0, 0, 0));
        PastPaperChecker.setText("Past papers required?");
        PastPaperChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastPaperCheckerActionPerformed(evt);
            }
        });
        getContentPane().add(PastPaperChecker, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        DateTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DateTextBox.setForeground(new java.awt.Color(0, 0, 0));
        DateTextBox.setToolTipText("");
        DateTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextBoxActionPerformed(evt);
            }
        });
        DateTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DateTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(DateTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 120, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 40, -1, -1));

        GradeTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GradeTextBox.setForeground(new java.awt.Color(0, 0, 0));
        GradeTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeTextBoxActionPerformed(evt);
            }
        });
        GradeTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GradeTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(GradeTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 50, -1));

        HourTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        HourTextBox.setForeground(new java.awt.Color(0, 0, 0));
        HourTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourTextBoxActionPerformed(evt);
            }
        });
        HourTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HourTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(HourTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 30, -1));

        FirstNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FirstNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        FirstNameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameTextBoxMouseClicked(evt);
            }
        });
        FirstNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextBoxActionPerformed(evt);
            }
        });
        FirstNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstNameTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(FirstNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, -1));

        LastNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LastNameTextBox.setForeground(new java.awt.Color(0, 0, 0));
        LastNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextBoxActionPerformed(evt);
            }
        });
        LastNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(LastNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 120, -1));

        BookNowButton.setBackground(new java.awt.Color(255, 102, 0));
        BookNowButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BookNowButton.setForeground(new java.awt.Color(0, 0, 0));
        BookNowButton.setText("Book Now");
        BookNowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookNowButtonMouseClicked(evt);
            }
        });
        BookNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BookNowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 230, 70));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        TimeErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TimeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        TimeErrorMessage.setText("    ");
        getContentPane().add(TimeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 380, -1));

        FirstNameErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        FirstNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        FirstNameErrorMessage.setText("    ");
        getContentPane().add(FirstNameErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 380, 20));

        LastNameErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        LastNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        LastNameErrorMessage.setText("     ");
        getContentPane().add(LastNameErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 380, -1));

        GradeErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        GradeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        GradeErrorMessage.setText("     ");
        getContentPane().add(GradeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 380, 20));

        DateErrorMessage.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DateErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        DateErrorMessage.setText("    ");
        getContentPane().add(DateErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 380, -1));

        SuccesfulMessage.setForeground(new java.awt.Color(51, 204, 0));
        SuccesfulMessage.setText("        ");
        getContentPane().add(SuccesfulMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 430, 150, -1));

        MinTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MinTextBox.setForeground(new java.awt.Color(0, 0, 0));
        MinTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinTextBoxActionPerformed(evt);
            }
        });
        MinTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MinTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(MinTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 30, -1));

        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Peters\\Documents\\NetBeansProjects\\DVT2024\\resources\\Looking-for-a-tutor.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 150));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PastPaperCheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastPaperCheckerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PastPaperCheckerActionPerformed

    private void DateTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTextBoxActionPerformed

    private void GradeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTextBoxActionPerformed

    private void HourTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourTextBoxActionPerformed

    private void FirstNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FirstNameTextBoxActionPerformed

    private void LastNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextBoxActionPerformed

    private void FirstNameTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameTextBoxMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_FirstNameTextBoxMouseClicked

    private void FirstNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_FirstNameTextBoxKeyPressed

    private void LastNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_LastNameTextBoxKeyPressed

    private void GradeTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GradeTextBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_GradeTextBoxKeyPressed

    private void DateTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTextBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_DateTextBoxKeyPressed

    private void HourTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HourTextBoxKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_HourTextBoxKeyPressed

    private void BookNowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookNowButtonMouseClicked

        String output = "";
        boolean fNameCheck = false;
        boolean lNameCheck = false;
        boolean GradeCheck = false;
        boolean DateCheck = false;
        boolean TimeCheck = false;

        if (FirstNameTextBox.getText().isEmpty()) {
            FirstNameErrorMessage.setText("Please enter your First Name");
        } else {
            if (Validator.ValidateString(FirstNameTextBox.getText())) {
                FirstNameErrorMessage.setText("");
                output += FirstNameTextBox.getText() + "#";
                fNameCheck = true;
            } else {
                FirstNameErrorMessage.setText("Please enter a valid Name ");
            }
        }

        if (LastNameTextBox.getText().isEmpty()) {
            LastNameErrorMessage.setText("Please enter your Last Name");
        } else {
            if (Validator.ValidateString(LastNameTextBox.getText())) {
                LastNameErrorMessage.setText("");
                output += LastNameTextBox.getText() + "#";
                lNameCheck = true;
            } else {
                LastNameErrorMessage.setText("Please enter a valid Name");
            }
        }

        if (GradeTextBox.getText().isEmpty()) {
            GradeErrorMessage.setText("Please enter your Grade");
        } else {
            if (Validator.ValidateRange(GradeTextBox.getText(), 1, 12)) {
                GradeErrorMessage.setText("");
                output += GradeTextBox.getText() + "#";
                GradeCheck = true;
            } else {
                GradeErrorMessage.setText("Please input a valid Grade (1 to 12)");
            }
        }
        
        output += SubjectList.getSelectedItem() + "#";

        if (DateTextBox.getText().isEmpty()) {
            DateErrorMessage.setText("Please enter the Date of your session");
        } else {
            if (Validator.ValidateDateFormat(DateTextBox.getText())) {

                if (Validator.ValidateLogic(DateTextBox.getText())) {
                    DateErrorMessage.setText("");
                    output += DateTextBox.getText() + "#";
                    DateCheck = true;

                } else {
                    DateErrorMessage.setText("Please enter a valid year");
                }
            } else {
                DateErrorMessage.setText("Please Input the correct Format of the Date (eg. 02/05/2024)");
            }

        }

        if (HourTextBox.getText().isEmpty()) {
            TimeErrorMessage.setText("Please enter the Hour of your session");
        }
        if (MinTextBox.getText().isEmpty()) {
            TimeErrorMessage.setText("Please enter the Minutes of your session");
        }
        
        if (HourTextBox.getText().isEmpty() && MinTextBox.getText().isEmpty()) {
            TimeErrorMessage.setText("Please enter the Time of your session");
        } else {
            if (Validator.ValidateRange(HourTextBox.getText(), 5, 19) && Validator.ValidateRange(MinTextBox.getText(), 0, 59)) {
                TimeErrorMessage.setText("");
                output += HourTextBox.getText()+":"+ MinTextBox.getText() +"#";
                TimeCheck = true;
            } else {
                TimeErrorMessage.setText("Please choose a Time between 05h00 and 19h00");
            }
        }

        
        output += PastPaperChecker.isSelected();
        if(fNameCheck && lNameCheck && GradeCheck && DateCheck && TimeCheck){
            System.out.println(output);
            SuccesfulMessage.setText("Booked Succesfully");
        }
    }//GEN-LAST:event_BookNowButtonMouseClicked

    private void MinTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinTextBoxActionPerformed

    private void MinTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MinTextBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinTextBoxKeyPressed

    private void BookNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNowButton;
    private javax.swing.JLabel DateErrorMessage;
    private javax.swing.JTextField DateTextBox;
    private javax.swing.JLabel FirstNameErrorMessage;
    private javax.swing.JTextField FirstNameTextBox;
    private javax.swing.JLabel GradeErrorMessage;
    private javax.swing.JTextField GradeTextBox;
    private javax.swing.JTextField HourTextBox;
    private javax.swing.JLabel LastNameErrorMessage;
    private javax.swing.JTextField LastNameTextBox;
    private javax.swing.JTextField MinTextBox;
    private javax.swing.JCheckBox PastPaperChecker;
    private javax.swing.JComboBox<String> SubjectList;
    private javax.swing.JLabel SuccesfulMessage;
    private javax.swing.JLabel TimeErrorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
