/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Validator;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author colep
 */
public class DVT extends javax.swing.JFrame {

    /**
     * Creates new form DVT
     */
    public DVT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SubjectList = new javax.swing.JComboBox<>();
        PastPaperChecker = new javax.swing.JCheckBox();
        DateTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GradeTextBox = new javax.swing.JTextField();
        HourTextBox = new javax.swing.JTextField();
        FirstNameTextBox = new javax.swing.JTextField();
        LastNameTextBox = new javax.swing.JTextField();
        BookNowButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TimeErrorMessage = new javax.swing.JLabel();
        FirstNameErrorMessage = new javax.swing.JLabel();
        LastNameErrorMessage = new javax.swing.JLabel();
        GradeErrorMessage = new javax.swing.JLabel();
        DateErrorMessage = new javax.swing.JLabel();
        JobSuccesfulMessage = new javax.swing.JLabel();
        MinTextBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tutor Booking");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 56));
        jLabel1.setMinimumSize(new java.awt.Dimension(75, 56));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, -1, -1));

        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Subject:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setText("Grade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setText("Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel7.setText("Time:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        SubjectList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SubjectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Afrikaans", "English", "Coding", "Art", "Physics", "Biology", "Geography", "History" }));
        getContentPane().add(SubjectList, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        PastPaperChecker.setText("Past papers required?");
        PastPaperChecker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastPaperCheckerActionPerformed(evt);
            }
        });
        getContentPane().add(PastPaperChecker, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        DateTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DateTextBox.setForeground(new java.awt.Color(153, 153, 153));
        DateTextBox.setToolTipText("");
        DateTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextBoxActionPerformed(evt);
            }
        });
        DateTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DateTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(DateTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 40, -1, -1));

        GradeTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        GradeTextBox.setForeground(new java.awt.Color(153, 153, 153));
        GradeTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeTextBoxActionPerformed(evt);
            }
        });
        GradeTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GradeTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(GradeTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 50, -1));

        HourTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        HourTextBox.setForeground(new java.awt.Color(153, 153, 153));
        HourTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourTextBoxActionPerformed(evt);
            }
        });
        HourTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HourTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(HourTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 309, 30, -1));

        FirstNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FirstNameTextBox.setForeground(new java.awt.Color(153, 153, 153));
        FirstNameTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameTextBoxMouseClicked(evt);
            }
        });
        FirstNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextBoxActionPerformed(evt);
            }
        });
        FirstNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstNameTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(FirstNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 120, -1));

        LastNameTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LastNameTextBox.setForeground(new java.awt.Color(153, 153, 153));
        LastNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextBoxActionPerformed(evt);
            }
        });
        LastNameTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(LastNameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 120, -1));

        BookNowButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BookNowButton.setText("Book Now");
        BookNowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookNowButtonMouseClicked(evt);
            }
        });
        getContentPane().add(BookNowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 230, 70));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        TimeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        TimeErrorMessage.setText("    ");
        getContentPane().add(TimeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 260, -1));

        FirstNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        FirstNameErrorMessage.setText("    ");
        getContentPane().add(FirstNameErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 260, 20));

        LastNameErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        LastNameErrorMessage.setText("     ");
        getContentPane().add(LastNameErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, -1));

        GradeErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        GradeErrorMessage.setText("     ");
        getContentPane().add(GradeErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 260, 20));

        DateErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        DateErrorMessage.setText("    ");
        getContentPane().add(DateErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 260, -1));

        JobSuccesfulMessage.setForeground(new java.awt.Color(51, 204, 0));
        JobSuccesfulMessage.setText("        ");
        getContentPane().add(JobSuccesfulMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 430, 150, -1));

        MinTextBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MinTextBox.setForeground(new java.awt.Color(153, 153, 153));
        MinTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinTextBoxActionPerformed(evt);
            }
        });
        MinTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MinTextBoxKeyPressed(evt);
            }
        });
        getContentPane().add(MinTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 309, 30, -1));

        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 310, -1, -1));

        jLabel11.setText("Hours : 5am-7pm");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PastPaperCheckerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastPaperCheckerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PastPaperCheckerActionPerformed

    private void DateTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTextBoxActionPerformed

    private void GradeTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeTextBoxActionPerformed

    private void HourTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourTextBoxActionPerformed

    private void FirstNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FirstNameTextBoxActionPerformed

    private void LastNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextBoxActionPerformed

    private void FirstNameTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameTextBoxMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FirstNameTextBoxMouseClicked

    private void FirstNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextBoxKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FirstNameTextBoxKeyPressed

    private void LastNameTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextBoxKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_LastNameTextBoxKeyPressed

    private void GradeTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GradeTextBoxKeyPressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_GradeTextBoxKeyPressed

    private void DateTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTextBoxKeyPressed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_DateTextBoxKeyPressed

    private void HourTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HourTextBoxKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_HourTextBoxKeyPressed

    private void BookNowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookNowButtonMouseClicked
       
        boolean pastpaper = PastPaperChecker.isSelected();
        
        //Format Check
        if(!Validator.ValidateDateFormat(DateTextBox.getText())){
            DateErrorMessage.setText("Please Input the correct Format of the Date");
        }
        
        //Logic Check
        if(Validator.ValidateDateFormat(DateTextBox.getText()) && !Validator.ValidateLogic(dateStr))
        
        
        
        //Range Check
        if(!Validator.ValidateRange(Integer.parseInt(GradeTextBox.getText()), 1, 12)){
           GradeErrorMessage.setText("Please input a valid Grade");
        }
        if(!Validator.ValidateRange(Integer.parseInt(HourTextBox.getText()), 05, 19)){
            TimeErrorMessage.setText("Please input a valid Time");
        }
        
        
        //Presence Check
        if (FirstNameTextBox.getText().equalsIgnoreCase("")){
            FirstNameErrorMessage.setText("Enter First Name");
        }
        
        if (LastNameTextBox.getText().equalsIgnoreCase("")){
            LastNameErrorMessage.setText("Enter Last Name");
        }
        
        if (GradeTextBox.getText().equalsIgnoreCase("")){
            GradeErrorMessage.setText("Enter Grade");
        }
        
        if (DateTextBox.getText().equalsIgnoreCase("")){
            DateErrorMessage.setText("Enter Date");
        }
        
        if (HourTextBox.getText().equalsIgnoreCase("")){
            TimeErrorMessage.setText("Enter Hour");
        }
        if (MinTextBox.getText().equalsIgnoreCase("")){
            TimeErrorMessage.setText("Enter Minute");
        }
        if (HourTextBox.getText().equalsIgnoreCase("") && MinTextBox.getText().equalsIgnoreCase("") ){
            TimeErrorMessage.setText("Enter Time");
        }
        
        
        
       
        
        
        
        
        
        
    }//GEN-LAST:event_BookNowButtonMouseClicked

    private void MinTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinTextBoxActionPerformed

    private void MinTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MinTextBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinTextBoxKeyPressed
  
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNowButton;
    private javax.swing.JLabel DateErrorMessage;
    private javax.swing.JTextField DateTextBox;
    private javax.swing.JLabel FirstNameErrorMessage;
    private javax.swing.JTextField FirstNameTextBox;
    private javax.swing.JLabel GradeErrorMessage;
    private javax.swing.JTextField GradeTextBox;
    private javax.swing.JTextField HourTextBox;
    private javax.swing.JLabel JobSuccesfulMessage;
    private javax.swing.JLabel LastNameErrorMessage;
    private javax.swing.JTextField LastNameTextBox;
    private javax.swing.JTextField MinTextBox;
    private javax.swing.JCheckBox PastPaperChecker;
    private javax.swing.JComboBox<String> SubjectList;
    private javax.swing.JLabel TimeErrorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
